language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: 1.8.0
      before_script:
        # libc 0.2.34 started using #[deprecated]
        - cargo generate-lockfile
        - cargo update --package libc --precise 0.2.33
sudo: false
script:
  - cargo build --verbose
  - ./ci/test_full.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
