[package]
authors = ["The Rust Project Developers"]
description = "Rational numbers implementation for Rust"
documentation = "https://docs.rs/num-rational"
homepage = "https://github.com/rust-num/num-rational"
keywords = ["mathematics", "numerics"]
categories = [ "algorithms", "data-structures", "science" ]
license = "MIT/Apache-2.0"
name = "num-rational"
repository = "https://github.com/rust-num/num-rational"
version = "0.1.41"
readme = "README.md"

[dependencies]

[dependencies.num-bigint]
optional = true
version = "0.1.32"

[dependencies.num-integer]
version = "0.1.32"

[dependencies.num-traits]
version = "0.1.32"

[dependencies.rustc-serialize]
optional = true
version = "0.3.19"

[dependencies.serde]
optional = true
version = ">= 0.7.0, < 0.9.0"

[features]
default = ["bigint", "rustc-serialize"]
bigint = ["num-bigint"]
